name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-default:
    runs-on: ubuntu-latest
    env:
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Test default (no features)
        run: cargo test --no-default-features

  test-rocket:
    runs-on: ubuntu-latest
    env:
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Test with Rocket feature
        run: cargo test --features rocket
